export { HomePage } from './home'
export { ProfileSetupPage } from './profile-setup'
export { TournamentBrowsePage } from './tournament-browse'
export { TournamentCreatePage } from './tournament-create'
export { TournamentSetupPage } from './tournament-setup'
export { TournamentDetailsPage } from './tournament-details'
export { MatchDetailsPage } from './match-details'
export { TeamDetailsPage } from './team-details'
export { TeamProfilePage } from './team-profile'
export { PlayerProfilePage } from './player-profile'
export { MatchSchedulePage } from './match-schedule'
export { UserDashboardPage } from './user-dashboard'
export { AuthPage } from './auth'
export { FeaturesPage } from './features'
export { TeamsPlayersPage } from './teams-players'
export { default as SponsorPage } from './sponsor'
